apiVersion: v1
kind: Service
metadata:
  name: scalable-app-service
  labels:
    app: scalable-app
spec:
  selector:
    app: scalable-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: ClusterIP
